fs      = require 'fs'
{print} = require 'sys'
{spawn} = require 'child_process'

log = (data) -> print data.toString()

task 'build', 'Build and watch the CoffeeScript source files', ->
  coffee = spawn 'coffee', ['-cw', '-o', 'lib', 'src']
  coffee.stdout.on 'data', log